var baseColor = "#222";

var P_RADIUS = 7;

var IDOLS_DATA = [
  {id: 1, part:"AS", region: "Vo", name:"天海春香", color:"#e22b30"},
  {id: 2, part:"AS", region: "Vo", name:"如月千早", color:"#2743d2"},
  {id: 4, part:"AS", region: "Vi", name:"萩原雪歩", color:"#d3dde9"},
  {id: 5, part:"AS", region: "Da", name:"高槻やよい", color:"#f39939"},
  {id: 9, part:"AS", region: "Vi", name:"秋月律子", color:"#01a860"},
  {id:10, part:"AS", region: "Vo", name:"三浦あずさ", color:"#9238be"},
  {id: 7, part:"AS", region: "Vo", name:"水瀬伊織", color:"#fd99e1"},
  {id: 6, part:"AS", region: "Da", name:"菊地真", color:"#515558"},
  {id:12, part:"AS", region: "Vi", name:"双海真美", color:"#ffe43f"},
  {id:11, part:"AS", region: "Vi", name:"双海亜美", color:"#ffe43f"},
  {id: 3, part:"AS", region: "Vi", name:"星井美希", color:"#b4e04b"},
  {id:13, part:"AS", region: "Da", name:"我那覇響", color:"#01adb9"},
  {id: 8, part:"AS", region: "Vo", name:"四条貴音", color:"#a6126a"},
  {id:16, part:"ML", region: "Vi", name:"伊吹翼", color:"#fed552"},
  {id:32, part:"ML", region: "Da", name:"エミリー", color:"#554171"},
  {id:40, part:"ML", region: "Da", name:"大神環", color:"#ee762e"},
  {id:14, part:"ML", region: "Vo", name:"春日未来", color:"#ea5b76"},
  {id:48, part:"ML", region: "Da", name:"北上麗花", color:"#6bb6b0"},
  {id:33, part:"ML", region: "Vi", name:"北沢志保", color:"#afa690"},
  {id:35, part:"ML", region: "Vo", name:"木下ひなた", color:"#d1342c"},
  {id:29, part:"ML", region: "Da", name:"高坂海美", color:"#e9739b"},
  {id:19, part:"ML", region: "Da", name:"佐竹美奈子", color:"#58a6dc"},
  {id:45, part:"ML", region: "Vi", name:"篠宮可憐", color:"#b63b40"},
  {id:18, part:"ML", region: "Da", name:"島原エレナ", color:"#9bce92"},
  {id:50, part:"ML", region: "Vo", name:"ジュリア", color:"#d7385f"},
  {id:49, part:"ML", region: "Vi", name:"周防桃子", color:"#efb864"},
  {id:27, part:"ML", region: "Vo", name:"高山紗代子", color:"#7f6575"},
  {id:17, part:"ML", region: "Vo", name:"田中琴葉", color:"#92cfbb"},
  {id:31, part:"ML", region: "Vo", name:"天空橋朋花", color:"#bee3e3"},
  {id:21, part:"ML", region: "Vi", name:"徳川まつり", color:"#5abfb7"},
  {id:20, part:"ML", region: "Vi", name:"所恵美", color:"#454341"},
  {id:41, part:"ML", region: "Vi", name:"豊川風花", color:"#7278a8"},
  {id:30, part:"ML", region: "Vi", name:"中谷育", color:"#f7e78e"},
  {id:47, part:"ML", region: "Da", name:"永吉昴", color:"#aeb49c"},
  {id:26, part:"ML", region: "Vi", name:"七尾百合子", color:"#c7b83c"},
  {id:38, part:"ML", region: "Vi", name:"二階堂千鶴", color:"#f19557"},
  {id:23, part:"ML", region: "Da", name:"野々原茜", color:"#eb613f"},
  {id:22, part:"ML", region: "Vo", name:"箱崎星梨花", color:"#ed90ba"},
  {id:39, part:"ML", region: "Da", name:"馬場このみ", color:"#f1becb"},
  {id:43, part:"ML", region: "Da", name:"福田のり子", color:"#eceb70"},
  {id:34, part:"ML", region: "Da", name:"舞浜歩", color:"#e25a9b"},
  {id:44, part:"ML", region: "Da", name:"真壁瑞希", color:"#99b7dc"},
  {id:28, part:"ML", region: "Vo", name:"松田亜利沙", color:"#b54461"},
  {id:42, part:"ML", region: "Vi", name:"宮尾美也", color:"#f19557"},
  {id:15, part:"ML", region: "Vo", name:"最上静香", color:"#6495cf"},
  {id:24, part:"ML", region: "Vo", name:"望月杏奈", color:"#7e6ca8"},
  {id:46, part:"ML", region: "Vi", name:"百瀬莉緒", color:"#f19591"},
  {id:36, part:"ML", region: "Vo", name:"矢吹可奈", color:"#f5ad3b"},
  {id:37, part:"ML", region: "Da", name:"横山奈緒", color:"#788bc5"},
  {id:25, part:"ML", region: "Vi", name:"ロコ", color:"#fff03c"}
];
